"""add calllog status and event type fields

Revision ID: 91695c4faf08
Revises: 53e00c7fefa0
Create Date: 2026-01-28 20:06:13.618549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91695c4faf08'
down_revision: Union[str, Sequence[str], None] = '53e00c7fefa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('raw_event_type', sa.String(length=50), nullable=True))
    op.add_column('call_logs', sa.Column('complaint_status', sa.String(length=20), nullable=True))
    op.add_column('call_logs', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'created_at')
    op.drop_column('call_logs', 'complaint_status')
    op.drop_column('call_logs', 'raw_event_type')
    # ### end Alembic commands ###
